apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-xxx
  template:
    metadata:
      labels:
        app: nginx-xxx
    spec:
      containers:
      - name: nginx
        image: buxybox
        command:
        - sh
        - -c
        args:
        - sleep
        - infinity
        volumeMounts:
        - name: vol-1
          mountPath: /nfs-data/
      volumes:
      - name: vol-1
        persistentVolumeClaim:
          claimName: pvc-1
