apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  storageClassName: openshift-storage.nfs.csi.ceph.com
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
